Resources: 
 Parameters:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Chat GPT API Key
      Value: NA
      Name: ${file(env.yml):ParameterName}

 ApiKey:
  Type: AWS::ApiGateway::ApiKey
  Properties:
    Name: "ChatGPTAPIKey"
    Description: Chat GPT API Key
    Enabled: true