Resources: 
 Parameters:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: Chat GPT API Key from Open AI
      Value: NA
      Name: ${file(env.yml):ParameterName}

 ApiKey:
  Type: AWS::ApiGateway::ApiKey
  Properties:
    Name: "ChatGPTAPIKey"
    Description: Chat GPT API Key for API Gateway
    Enabled: true

 UsagePlan:
  Type: AWS::ApiGateway::UsagePlan
  Properties:
    Description: Chat GPT API Usage plan
    UsagePlanName: Chat GPT API Usage plan